version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: ./dockerfiles/dockerfile
        volumes:
            - '.:/usr/src/app'
            - /usr/src/app/node_modules
        ports:
            - '80:3000'
        command: 'npm start -- --port 3000'
